import { NextResponse } from 'next/server'

const TELEGRAM_BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN
const TELEGRAM_CHAT_ID = process.env.TELEGRAM_CHAT_ID

interface TelegramPayload {
  title: string
  description: string
  timestamp?: string
  imageBase64?: string // Base64 encoded image data
}

// Send text message to Telegram
async function sendTelegramMessage(text: string): Promise<boolean> {
  if (!TELEGRAM_BOT_TOKEN || !TELEGRAM_CHAT_ID) {
    console.error('[Telegram] Credentials not configured')
    return false
  }

  try {
    console.log(`[Telegram] Sending message to chat_id: ${TELEGRAM_CHAT_ID}`)
    const response = await fetch(
      `https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          chat_id: TELEGRAM_CHAT_ID,
          text: text,
          parse_mode: 'HTML',
        }),
      }
    )

    const data = await response.json()
    console.log('[Telegram] sendMessage response:', JSON.stringify(data))
    if (!data.ok) {
      console.error('[Telegram] sendMessage error:', data.error_code, data.description)
      return false
    }
    return true
  } catch (error) {
    console.error('[Telegram] Error sending message:', error)
    return false
  }
}

// Send photo to Telegram
async function sendTelegramPhoto(imageBase64: string, caption: string): Promise<boolean> {
  if (!TELEGRAM_BOT_TOKEN || !TELEGRAM_CHAT_ID) {
    console.error('[Telegram] Credentials not configured')
    return false
  }

  try {
    const base64Data = imageBase64.includes(',') 
      ? imageBase64.split(',')[1] 
      : imageBase64

    const imageBuffer = Buffer.from(base64Data, 'base64')
    const formData = new FormData()
    formData.append('chat_id', TELEGRAM_CHAT_ID)

    // Strip HTML tags - plain text is safer for captions to avoid parse errors
    const plainCaption = caption.replace(/<[^>]*>/g, '').replace(/\n+/g, '\n').trim()
    formData.append('caption', plainCaption.substring(0, 1024))

    const blob = new Blob([imageBuffer], { type: 'image/jpeg' })
    formData.append('photo', blob, 'alert_frame.jpg')

    console.log(`[Telegram] Sending photo to chat_id: ${TELEGRAM_CHAT_ID}`)
    const response = await fetch(
      `https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendPhoto`,
      { method: 'POST', body: formData }
    )

    const data = await response.json()
    console.log('[Telegram] sendPhoto response:', JSON.stringify(data))
    if (!data.ok) {
      console.error('[Telegram] sendPhoto error:', data.error_code, data.description)
      return false
    }
    return true
  } catch (error) {
    console.error('[Telegram] Error sending photo:', error)
    return false
  }
}

export async function POST(request: Request) {
  console.log('Telegram notification API hit!')
  
  try {
    // Check if Telegram credentials are configured
    if (!TELEGRAM_BOT_TOKEN) {
      console.error('TELEGRAM_BOT_TOKEN is not set in environment variables')
      return NextResponse.json(
        { error: 'Telegram bot not configured. Please set TELEGRAM_BOT_TOKEN.' },
        { status: 500 }
      )
    }

    if (!TELEGRAM_CHAT_ID) {
      console.error('TELEGRAM_CHAT_ID is not set in environment variables')
      return NextResponse.json(
        { error: 'Telegram chat ID not configured. Please set TELEGRAM_CHAT_ID.' },
        { status: 500 }
      )
    }

    const { title, description, timestamp, imageBase64 }: TelegramPayload = await request.json()

    // Format the alert message
    const alertMessage = `
🚨 <b>NAZAR-AI SECURITY ALERT</b> 🚨

<b>⚠️ ${title}</b>

📝 <b>Description:</b>
${description}

🕐 <b>Time:</b> ${timestamp || new Date().toLocaleString()}

<i>This alert was generated by Nazar-AI's real-time AI monitoring system.</i>
    `.trim()

    let success = false

    // If image is provided, send photo with caption
    if (imageBase64) {
      console.log('Sending Telegram photo notification...')
      success = await sendTelegramPhoto(imageBase64, alertMessage)
      
      // If photo fails, fallback to text message
      if (!success) {
        console.log('Photo send failed, falling back to text message...')
        success = await sendTelegramMessage(alertMessage)
      }
    } else {
      // No image, send text message only
      console.log('Sending Telegram text notification...')
      success = await sendTelegramMessage(alertMessage)
    }

    if (success) {
      console.log('Telegram notification sent successfully')
      return NextResponse.json({ 
        success: true, 
        message: 'Telegram notification sent successfully' 
      })
    } else {
      return NextResponse.json(
        { error: 'Failed to send Telegram notification' },
        { status: 500 }
      )
    }

  } catch (error) {
    console.error('Unexpected error in Telegram API:', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    )
  }
}
