import { Resend } from 'resend'
import { NextResponse } from 'next/server'
// import { createClient } from '@/utils/supabase/server' 

// Initialize Resend only when needed
let resend: Resend | null = null;

function getResendClient() {
  if (!resend && process.env.RESEND_API_KEY) {
    resend = new Resend(process.env.RESEND_API_KEY);
  }
  return resend;
}

export async function POST(request: Request) {
  console.log('API route hit!')
  try {
    // Check if RESEND_API_KEY is set
    if (!process.env.RESEND_API_KEY) {
      console.error('RESEND_API_KEY is not set in environment variables')
      return NextResponse.json({ error: 'Email service not configured' }, { status: 500 })
    }

    const { title, description } = await request.json()
    console.log('Sending email to: webaiagent2@gmail.com')

    const resendClient = getResendClient();
    if (!resendClient) {
      return NextResponse.json({ error: 'Email service not configured' }, { status: 500 })
    }

    const { data, error } = await resendClient.emails.send({
      from: 'Nazar-AI <onboarding@resend.dev>',
      to: ['webaiagent2@gmail.com'], // Security alert recipient
      subject: `[ALERT] ${title}`,
      html: `
        <h2>${title}</h2>
        <p>${description}</p>
        <p><em>This alert was generated by Nazar-AI's real-time monitoring system.</em></p>
      `
    })

    if (error) {
      console.error('Resend API error:', error)
      return NextResponse.json({ error })
    }
    console.log('Email sent successfully:', data)

    return NextResponse.json({ data })
  } catch (error) {
    console.error('Unexpected error in email API:', error)
    return NextResponse.json({ error: error instanceof Error ? error.message : 'Unknown error' })
  }
}
