import { NextResponse } from 'next/server'

const TWILIO_ACCOUNT_SID = process.env.TWILIO_ACCOUNT_SID
const TWILIO_AUTH_TOKEN = process.env.TWILIO_AUTH_TOKEN
const TWILIO_WHATSAPP_FROM = process.env.TWILIO_WHATSAPP_FROM || process.env.TWILIO_PHONE_NUMBER
const TWILIO_WHATSAPP_TO = process.env.TWILIO_WHATSAPP_TO

interface WhatsAppPayload {
  title: string
  description: string
  timestamp?: string
  imageBase64?: string
}

function normalizeWhatsAppNumber(value?: string): string | undefined {
  if (!value) {
    return undefined
  }

  return value.startsWith('whatsapp:') ? value : `whatsapp:${value}`
}

async function sendWhatsAppMessage(message: string): Promise<{ ok: boolean; error?: string }> {
  if (!TWILIO_ACCOUNT_SID || !TWILIO_AUTH_TOKEN || !TWILIO_WHATSAPP_FROM || !TWILIO_WHATSAPP_TO) {
    return { ok: false, error: 'Twilio WhatsApp credentials are not fully configured' }
  }

  const from = normalizeWhatsAppNumber(TWILIO_WHATSAPP_FROM)
  const to = normalizeWhatsAppNumber(TWILIO_WHATSAPP_TO)

  if (!from || !to) {
    return { ok: false, error: 'Invalid Twilio WhatsApp phone number format' }
  }

  const auth = Buffer.from(`${TWILIO_ACCOUNT_SID}:${TWILIO_AUTH_TOKEN}`).toString('base64')

  const body = new URLSearchParams({
    From: from,
    To: to,
    Body: message,
  })

  try {
    const response = await fetch(
      `https://api.twilio.com/2010-04-01/Accounts/${TWILIO_ACCOUNT_SID}/Messages.json`,
      {
        method: 'POST',
        headers: {
          Authorization: `Basic ${auth}`,
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        body,
      }
    )

    const data = await response.json()

    if (!response.ok) {
      const errorMessage = data?.message || 'Twilio API request failed'
      console.error('Twilio WhatsApp API error:', errorMessage)
      return { ok: false, error: errorMessage }
    }

    return { ok: true }
  } catch (error) {
    console.error('Error sending Twilio WhatsApp message:', error)
    return {
      ok: false,
      error: error instanceof Error ? error.message : 'Unknown Twilio error',
    }
  }
}

export async function POST(request: Request) {
  console.log('WhatsApp notification API hit!')

  try {
    const { title, description, timestamp, imageBase64 }: WhatsAppPayload = await request.json()

    const alertMessage = [
      '🚨 NAZAR-AI SECURITY ALERT 🚨',
      '',
      `⚠️ ${title}`,
      '',
      '📝 Description:',
      description,
      '',
      `🕐 Time: ${timestamp || new Date().toLocaleString()}`,
      imageBase64 ? '📷 Frame captured in Nazar-AI dashboard.' : '',
      "This alert was generated by Nazar-AI's real-time AI monitoring system.",
    ]
      .filter((line, index, arr) => !(line === '' && arr[index - 1] === ''))
      .join('\n')

    const result = await sendWhatsAppMessage(alertMessage)

    if (!result.ok) {
      return NextResponse.json(
        { error: result.error || 'Failed to send WhatsApp notification' },
        { status: 500 }
      )
    }

    return NextResponse.json({ success: true, message: 'WhatsApp notification sent successfully' })
  } catch (error) {
    console.error('Unexpected error in WhatsApp API:', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    )
  }
}
